server:
  servlet:
    context-path: /api

spring:
  application:
    name: board

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer_datasource-initialization: true #data.sql

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

jwt:
  issuer: "open-my-app"
  secret_key: Jaeyoon-thank-you-always-Fighting
